print("helllo world")
print("nama ahmad")
print("10 tkj 1")
print("tutor dapetin mu")
print("tutor retri deck")
print("saya suka sekali dengan turu")
print("masih pelajar")
print("rama cabul")
print("pengen jadi pengusaha")
print("apa")